language: go
sudo: false

go:
 - 1.7.x
 - 1.6
 - 1.5

services:
 - redis-server

install:
 - go get github.com/garyburd/redigo/redis
 - go get github.com/MasterOfBinary/redistypes

script:
 - go run main.go

notifications:
  email: false